.TH SCREENRULER 1 "May 4, 2008"

.SH NAME
screenruler \- a graphical ruler to measure objects on screen

.SH SYNOPSIS
\fBscreenruler\fP

.SH DESCRIPTION
\fBScreenRuler\fP is a simple graphical ruler which allows you to measure
horizontal or vertically any object on screen using different metric
systems (pixels, centimetres, inches, picas, points or as a percentage).
.PP
It was created for GNOME desktops and can be controled either using the
mouse or, if you need more precision, with the keyboard. If you need it,
it also has an option to keep on top of other windows.

.SH OPTIONS
As already said, \fBScreenRuler\fP is a graphical application, and as such it
takes no command line options. All configuration must be done using its
GTK interface.

.SH AUTHORS
\fBScreenRuler\fP was created by Ian McIntosh <ian@openanswers.org> and this
manual page was written by Siegfried-A. Gevatter <rainct@ubuntu.com>.

.SH LICENSE
\fBScreenRuler\fP has been released under the GNU General Public License,
version 2 or later.
